version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: clanarina_db
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    # show all queries
    command: "-c log_statement=all"
